# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ab395ad156022e402584e9ce00e09015094988c79419ed34486a94974ec6aeb08cb63121e8910366ce65b306885d6728a073b0f244d9e1f8b42715e57a3b6d3

test:
  secret_key_base: 0a9ea14a8cff17f0b8a4f49f5b8e5bafbaaa6223c21c53324d83bc40a0ac62b6a9d6dd5eaf201214b420efc944ac83da97ef4cf6f219e993cc0509fd81bbae60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
